package com.example.btl.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ListView;

import androidx.annotation.NonNull;
import androidx.fragment.app.Fragment;

import com.example.btl.R;
import com.example.btl.adapter.OnThiAdapter;
import com.example.btl.model.OnTap;

import java.util.ArrayList;

public class LuatGiaoThongFragment extends Fragment {
    private ListView lvCauhoiLiet;
    private ArrayList<OnTap> arrayOntap;
    private OnThiAdapter onTapAdapter;

    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_luat_giao_thong, container, false);
    }
    public void onViewStateRestored(@NonNull Bundle saveInstanceState) {
        super.onViewStateRestored(saveInstanceState);
        Anhxa();
        onTapAdapter = new OnThiAdapter(getActivity(), R.layout.dong_on_tap, arrayOntap);
        lvCauhoiLiet.setAdapter(onTapAdapter);
    }

    private void Anhxa() {
        lvCauhoiLiet = getActivity().findViewById(R.id.listViewCauhoiLiet);
        arrayOntap = new ArrayList<>();
        arrayOntap.add(new OnTap("Câu hỏi 1: Phần của đường bộ được sử dụng cho các phương tiện giao thông qua lại là gì?",
                "1. Phần mặt đường và lề đường.",
                "2. Phần đường xe chạy.",
                "3. Phần đường xe cơ giới.",
                null,
                "Đáp án: Phần đường xe chạy.",
                "Giải thích: Phần đường xe chạy là phần của đường bộ được sử dụng cho phương tiện giao thông qua lại.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 2: “Làn đường” là gì?",
                "1. Là một phần của phần đường xe chạy được chia theo chiều dọc của đường, sử dụng cho xe chạy.",
                "2. Là một phần của phần đường xe chạy được chia theo chiều dọc của đường, có bề rộng đủ cho xe chạy an toàn.",
                "3. Là đường cho xe ô tô chạy, dừng, đỗ an toàn.",
                null,
                "Đáp án: Là một phần của phần đường xe chạy được chia theo chiều dọc của đường, có bề rộng đủ cho xe chạy an toàn.",
                "Giải thích: Làn đường có bề rộng đủ cho xe chạy an toàn.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 3: Trong các khái niệm dưới đây, “dải phân cách” được hiểu như thế nào là đúng?",
                "1. Là bộ phận của đường để ngăn cách không cho các loại xe vào những nơi không được phép.",
                "2. Là bộ phận của đường để phân tách phần đường xe chạy và hành lang an toàn giao thông.",
                "3. Là bộ phận của đường để phân chia mặt đường thành hai chiều xe chạy riêng biệt hoặc để phân chia phần đường của xe cơ giới và xe thô sơ.",
                null,
                "Đáp án: Là bộ phận của đường để phân chia mặt đường thành hai chiều xe chạy riêng biệt hoặc để phân chia phần đường của xe cơ giới và xe thô sơ.",
                "Giải thích: Dải phân cách phân chia mặt đường thành hai chiều xe chạy riêng biệt.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 4: “Dải phân cách” trên đường bộ gồm những loại nào?",
                "1. Dải phân cách gồm loại cố định và loại di động.",
                "2. Dải phân cách gồm tường chống ồn, hộ lan cứng và hộ lan mềm.",
                "3. Dải phân cách gồm giá long môn và biển báo hiệu đường bộ.",
                null,
                "Đáp án: Dải phân cách gồm loại cố định và loại di động.",
                "Giải thích: Dải phân cách gồm cố định và di động.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 5: Người lái xe được hiểu như thế nào trong các khái niệm dưới đây?",
                "1. Là người điều khiển xe cơ giới.",
                "2. Là người điều khiển xe thô sơ.",
                "3. Là người điều khiển xe có súc vật kéo.",
                null,
                "Đáp án: Là người điều khiển xe cơ giới.",
                "Giải thích: Người lái xe là người điều khiển xe cơ giới.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 6: Đường mà trên đó phương tiện tham gia giao thông được các phương tiện giao thông đến từ các hướng khác nhường đường khi qua nơi đường giao nhau, được cắm biển báo hiệu đường ưu tiên là loại đường gì?",
                "1. Đường không ưu tiên.",
                "2. Đường tỉnh lộ.",
                "3. Đường quốc lộ.",
                "4. Đường ưu tiên.",
                "Đáp án: Đường ưu tiên.",
                "Giải thích: Đường ưu tiên được nhường đường khi qua nơi giao nhau.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 7: Khái niệm “phương tiện giao thông cơ giới đường bộ” được hiểu như thế nào là đúng?",
                "1. Gồm xe ô tô; máy kéo; xe mô tô hai bánh; xe mô tô ba bánh; xe gắn máy; xe cơ giới dùng cho người khuyết tật và xe máy chuyên dùng.",
                "2. Gồm ô tô; máy kéo; rơ moóc hoặc sơ mi rơ moóc được kéo bởi xe ô tô, máy kéo; xe mô tô hai bánh; xe mô tô ba bánh, xe gắn máy (kể cả xe máy điện) và các loại xe tương tự.",
                null,
                null,
                "Đáp án: Gồm ô tô; máy kéo; rơ moóc hoặc sơ mi rơ moóc được kéo bởi xe ô tô, máy kéo; xe mô tô hai bánh; xe mô tô ba bánh, xe gắn máy (kể cả xe máy điện) và các loại xe tương tự.",
                "Giải thích: Phương tiện giao thông cơ giới không có xe máy chuyên dùng.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 8: Khái niệm “phương tiện giao thông thô sơ đường bộ” được hiểu như thế nào là đúng?",
                "1. Gồm xe đạp (kể cả xe đạp máy, xe đạp điện), xe xích lô, xe lăn dùng cho người khuyết tật, xe súc vật kéo và các loại xe tương tự.",
                "2. Gồm xe đạp (kể cả xe đạp máy, xe đạp điện), xe gắn máy, xe cơ giới dùng cho người khuyết tật và xe máy chuyên dùng.",
                "3. Gồm xe ô tô, máy kéo, rơ moóc hoặc sơ mi rơ moóc được kéo bởi xe ô tô, máy kéo.",
                null,
                "Đáp án: Gồm xe đạp (kể cả xe đạp máy, xe đạp điện), xe xích lô, xe lăn dùng cho người khuyết tật, xe súc vật kéo và các loại xe tương tự.",
                "Giải thích: Phương tiện giao thông thô sơ không có xe máy chuyên dùng; xe ô tô.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 9: “Phương tiện tham gia giao thông đường bộ” gồm những loại nào?",
                "1. Phương tiện giao thông cơ giới đường bộ.",
                "2. Phương tiện giao thông thô sơ đường bộ và xe máy chuyên dùng.",
                "3. Cả ý 1 và ý 2.",
                null,
                "Đáp án: Cả ý 1 và ý 2.",
                "Giải thích: Phương tiện giao thông gồm tất cả các loại phương tiện.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 10: “Người tham gia giao thông đường bộ” gồm những đối tượng nào?",
                "1. Người điều khiển, người sử dụng phương tiện tham gia giao thông đường bộ.",
                "2. Người điều khiển, dẫn dắt súc vật; người đi bộ trên đường bộ.",
                "3. Cả ý 1 và ý 2.",
                null,
                "Đáp án: Cả ý 1 và ý 2.",
                "Giải thích: Người tham gia giao thông gồm người sử dụng phương tiện và người đi bộ.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 11: “Người điều khiển phương tiện tham gia giao thông đường bộ” gồm những đối tượng nào dưới đây?",
                "1. Người điều khiển xe cơ giới, người điều khiển xe thô sơ.",
                "2. Người điều khiển xe máy chuyên dùng tham gia giao thông đường bộ.",
                "3. Cả ý 1 và ý 2.",
                null,
                "Đáp án: Cả ý 1 và ý 2.",
                "Giải thích: Người điều khiển phương tiện gồm cả xe cơ giới và xe máy chuyên dùng.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 12: Khái niệm “người điều khiển giao thông” được hiểu như thế nào là đúng?",
                "1. Là người điều khiển phương tiện tham gia giao thông tại nơi thi công, nơi ùn tắc giao thông, ở bến phà, tại cầu đường bộ đi chung với đường sắt.",
                "2. Là cảnh sát giao thông, người được giao nhiệm vụ hướng dẫn giao thông tại nơi thi công, nơi ùn tắc giao thông, ở bến phà, tại cầu đường bộ đi chung với đường sắt.",
                "3. Là người tham gia giao thông tại nơi thi công, nơi ùn tắc giao thông, ở bến phà, tại cầu đường bộ đi chung với đường sắt.",
                null,
                "Đáp án: Là cảnh sát giao thông, người được giao nhiệm vụ hướng dẫn giao thông tại nơi thi công, nơi ùn tắc giao thông, ở bến phà, tại cầu đường bộ đi chung với đường sắt.",
                "Giải thích: Người điều khiển giao thông là cảnh sát giao thông.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 13: Trong các khái niệm dưới đây khái niệm “dừng xe” được hiểu như thế nào là đúng?",
                "1. Là trạng thái đứng yên của phương tiện giao thông không giới hạn thời gian để cho người lên, xuống phương tiện, xếp dỡ hàng hóa hoặc thực hiện công việc khác.",
                "2. Là trạng thái đứng yên tạm thời của phương tiện giao thông trong một khoảng thời gian cần thiết đủ để cho người lên, xuống phương tiện, xếp dỡ hàng hóa hoặc thực hiện công việc khác.",
                "3. Là trạng thái đứng yên của phương tiện giao thông không giới hạn thời gian giữa 02 lần vận chuyển hàng hóa hoặc hành khách.",
                null,
                "Đáp án: Là trạng thái đứng yên tạm thời của phương tiện giao thông trong một khoảng thời gian cần thiết đủ để cho người lên, xuống phương tiện, xếp dỡ hàng hóa hoặc thực hiện công việc khác.",
                "Giải thích: Dừng xe là đứng yên tạm thời.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 14: Khái niệm “đỗ xe” được hiểu như thế nào là đúng?",
                "1. Là trạng thái đứng yên của phương tiện giao thông có thời hạn trong một khoảng thời gian cần thiết đủ để cho người lên, xuống phương tiện, xếp dỡ hàng hóa hoặc thực hiện công việc khác.",
                "2. Là trạng thái đứng yên của phương tiện giao thông không giới hạn thời gian.",
                null,
                null,
                "Đáp án:  Là trạng thái đứng yên của phương tiện giao thông không giới hạn thời gian.",
                "Giải thích: Đỗ xe là đứng yên không giới hạn thời gian.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 15: Cuộc đua xe chỉ được thực hiện khi nào?",
                "1. Diễn ra trên đường phố không có người qua lại.",
                "2. Được người dân ủng hộ.",
                "3. Được cơ quan có thẩm quyền cấp phép.",
                null,
                "Đáp án: Được cơ quan có thẩm quyền cấp phép.",
                "Giải thích: Cuộc đua xe cần cấp phép.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 16: Người điều khiển phương tiện giao thông đường bộ mà trong cơ thể có chất ma túy có bị nghiêm cấm hay không?",
                "1. Bị nghiêm cấm.",
                "2. Không bị nghiêm cấm.",
                "3. Không bị nghiêm cấm, nếu có chất ma túy ở mức nhẹ, có thể điều khiển phương tiện tham gia giao thông.",
                null,
                "Đáp án: Bị nghiêm cấm.",
                "Giải thích: Cuộc đua xe cần cấp phép.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 17: Sử dụng rượu, bia khi lái xe, nếu bị " +
                "phát hiện thì bị xử lý như thế nào?",
                "1. Chỉ bị nhắc nhở.",
                "2. Bị xử phạt hành chính hoặc có thể bị xử lý hình sự tùy theo mức độ vi phạm.",
                "3. Không bị xử lý hình sự.",
                null,
                "Đáp án: Bị xử phạt hành chính hoặc có thể bị xử lý hình sự tùy theo mức độ vi phạm.",
                "Giải thích: Sử dụng rượu, bia khi lái xe bị phạt hành chính hoặc xử lý hình sự.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 18: Theo Luật phòng chống tác hại của rượu, bia, " +
                "đối tượng nào dưới đây bị cấm sử dụng rượu, bia khi tham gia giao thông?",
                "1. Người điều khiển: Xe ô tô, xe mô tô, xe đạp, xe gắn máy.",
                "2. Người ngồi phía sau người điều khiển xe cơ giới.",
                "3. Người đi bộ.",
                "4. Cả ý 1 và ý 2.",
                "Đáp án: Người điều khiển: Xe ô tô, xe mô tô, xe đạp, xe gắn máy.",
                "Giải thích: Người điều khiển bị cấm sử dụng rượu, bia khi tham gia giao thông.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 19: Hành vi điều khiển xe cơ giới chạy quá tốc độ quy định, giành đường, vượt ẩu có bị nghiêm cấm hay không?",
                "1. Bị nghiêm cấm tuỳ từng trường hợp.",
                "2. Không bị nghiêm cấm.",
                "3. Bị nghiêm cấm.",
                null,
                "Đáp án: Bị nghiêm cấm.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 20: Khi lái xe trong khu đô thị và đông dân cư trừ các khu vực có biển cấm sử dụng còi, người lái xe được sử dụng còi như thế nào trong các trường hợp dưới đây?",
                "1. Từ 22 giờ đêm đến 5 giờ sáng.",
                "2. Từ 5 giờ sáng đến 22 giờ tối.",
                "3. Từ 23 giờ đêm đến 5 giờ sáng hôm sau.",
                null,
                "Đáp án: Từ 5 giờ sáng đến 22 giờ tối.",
                "Giải thích: Chỉ sử dụng còi từ 5 giời sáng đến 22 giờ tối.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 21: Người lái xe sử dụng đèn như thế nào khi lái xe trong khu đô thị và đông dân cư vào ban đêm?",
                "1. Bất cứ đèn nào miễn là mắt nhìn rõ phía trước.",
                "2. Chỉ bật đèn chiếu xa (đèn pha) khi không nhìn rõ đường.",
                "3. Đèn chiếu xa (đèn pha) khi đường vắng, đèn pha chiếu gần (đèn cốt) khi có xe đi ngược chiều.",
                "4. Đèn chiếu gần (đèn cốt).",
                "Đáp án: Đèn chiếu gần (đèn cốt).",
                "Giải thích: Trong đô thị sử dụng đèn chiếu gần.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 22: Trong trường hợp đặc biệt, để được lắp đặt, sử dụng còi, đèn không đúng với thiết kế của nhà sản xuất đối với từng loại xe cơ giới bạn phải đảm bảo yêu cầu nào dưới đây?",
                "1. Phải đảm bảo phụ tùng do đúng nhà sản xuất đó cung cấp.",
                "2. Phải được chấp thuận của cơ quan có thẩm quyền.",
                "3. Phải là xe đăng ký và hoạt động tại các khu vực có địa hình phức tạp.",
                null,
                "Đáp án: Phải được chấp thuận của cơ quan có thẩm quyền.",
                "Giải thích: Lắp đặt còi đèn không đúng thiết kế phải được chấp thuận của cơ quan có thẩm quyền.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi liệt 23: Ở phần đường dành cho người đi bộ qua đường, trên cầu, đầu cầu, đường cao tốc, đường hẹp, đường dốc, tại nơi đường bộ giao nhau cùng mức với đường sắt có được quay đầu xe hay không ?",
                "1. Được phép.",
                "2. Không được phép.",
                "3. Tùy từng trường hợp.",
                null,
                "Đáp án: Không được phép.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 24: Bạn đang lái xe phía trước có một xe cảnh sát giao thông không phát tín hiệu ưu tiên bạn có được phép vượt hay không?",
                "1. Không được vượt.",
                "2. Được vượt khi đang đi trên cầu.",
                "3. Được phép vượt khi đi qua nơi giao nhau có ít phương tiện cùng tham gia giao thông.",
                "4. Được vượt khi đảm bảo an toàn.",
                "Đáp án: Được vượt khi đảm bảo an toàn.",
                "Giải thích: Được vượt khi xe không phát tín hiệu ưu tiên.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 25: Bạn đang lái xe phía trước có một xe cứu thương đang phát tín hiệu ưu tiên bạn có được phép vượt hay không?",
                "1. Không được vượt.",
                "2. Được vượt khi đang đi trên cầu.",
                "3. Được phép vượt khi đi qua nơi giao nhau có ít phương tiện cùng tham gia giao thông.",
                "4. Được vượt khi đảm bảo an toàn.",
                "Đáp án: Được vượt khi đảm bảo an toàn.",
                "Giải thích: Giải thích: Không được vượt khi đang phát tín hiệu ưu tiên.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 26: Người điều khiển xe mô tô hai bánh, ba bánh, xe gắn máy có được phép sử dụng xe để kéo hoặc đẩy các phương tiện khác khi tham gia giao thông không?",
                "1. Được phép.",
                "2. Nếu phương tiện được kéo, đẩy có khối lượng nhỏ hơn phương tiện của mình.",
                "3. Tùy trường hợp.",
                "4. Không được phép.",
                "Đáp án: Không được phép.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 27: Khi điều khiển xe mô tô hai bánh, xe mô tô ba bánh, xe gắn máy, những hành vi buông cả hai tay; sử dụng xe để kéo, đẩy xe khác, vật khác, sử dụng chân chống của xe quệt xuống đường khi xe đang chạy có được phép hay không?",
                "1. Được phép.",
                "2. Tùy trường hợp.",
                "3. Không được phép.",
                null,
                "Đáp án: Không được phép.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 28: Khi điều khiển xe mô tô hai bánh, xe mô tô ba bánh, xe gắn máy, những hành vi nào không được phép?",
                "1. Buông cả hai tay, sử dụng xe để kéo, đẩy xe khác, vật khác, sử dụng chân chống của xe quệt xuống đường khi xe đang chạy.",
                "2. Buông một tay, sử dụng xe để chở người hoặc hàng hoá để chân chạm xuống đất khi khởi hành.",
                "3. Đội mũ bảo hiểm; chạy xe đúng tốc độ quy định và chấp hành đúng quy tắc giao thông đường bộ.",
                "4. Chở người ngồi sau dưới 16 tuổi.",
                "Đáp án: Buông cả hai tay, sử dụng xe để kéo, đẩy xe khác, vật khác, sử dụng chân chống của xe quệt xuống đường khi xe đang chạy.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 29: Người ngồi trên xe mô tô hai bánh, ba bánh, xe gắn máy khi tham gia giao thông có được mang, vác vật cồng kềnh hay không?",
                "1. Được mang, vác tuỳ trường hợp cụ thể.",
                "2. Không được mang, vác.",
                "3. Được mang, vác nhưng phải đảm bảo an toàn.",
                "4. Được mang, vác tùy theo sức khỏe của bản thân.",
                "Đáp án: Không được mang, vác.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 30: Người ngồi trên xe mô tô hai bánh, xe mô tô ba bánh, xe gắn máy khi tham gia giao thông có được bám, kéo hoặc đẩy các phương tiện khác không?",
                "1. Được phép.",
                "2. Được làm trong trường hợp phương tiện của mình bị hỏng.",
                "3. Được kéo, đẩy trong trường hợp phương tiện khác bị hỏng.",
                "4. Không được phép.",
                "Đáp án: Không được phép.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 31: Người ngồi trên xe mô tô hai bánh, xe mô tô ba bánh, xe gắn máy khi tham gia giao thông có được sử dụng ô khi trời mưa hay không ?",
                "1. Được sử dụng.",
                "2. Chỉ người ngồi sau được sử dụng.",
                "3. Không được sử dụng.",
                "4. KĐược sử dụng nếu không có áo mưa.",
                "Đáp án: Không được sử dụng.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 32: Người có giấy phép lái xe mô tô hạng A1 không được phép điều khiển loại xe nào dưới đây?",
                "1. Xe mô tô có dung tích xi-lanh 125 cm3.",
                "2. Xe mô tô có dung tích xi-lanh từ 175 cm3 trở lên.",
                "3. Xe mô tô có dung tích xi-lanh 100 cm3.",
                null,
                "Đáp án: Xe mô tô có dung tích xi-lanh từ 175 cm3 trở lên.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 33: Hành vi sử dụng xe mô tô để kéo, đẩy xe mô tô khác bị hết xăng đến trạm mua xăng có được phép hay không?",
                "1. Chỉ được kéo nếu đã nhìn thấy trạm xăng.",
                "2. Chỉ được thực hiện trên đường vắng phương tiện cùng tham gia giao thông.",
                "3. Không được phép.",
                null,
                "Đáp án: Không được phép.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 34: Hành vi vận chuyển đồ vật cồng kềnh bằng xe mô tô, xe gắn máy khi tham gia giao thông có được phép hay không?",
                "1. Không được vận chuyển.",
                "2. Chỉ được vận chuyển khi đã chằng buộc cẩn thận.",
                "3. Chỉ được vận chuyển vật cồng kềnh trên xe máy nếu khoảng cách về nhà ngắn hơn 2 km.",
                null,
                "Đáp án: Không được vận chuyển.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 35: Người đủ bao nhiêu tuổi trở lên thì được điều khiển xe mô tô hai bánh, xe mô tô ba bánh có dung tích xi lanh từ 50 cm3 trở lên và các loại xe có kết cấu tương tự; xe ô tô tải, máy kéo có trọng tải dưới 3,5 tấn; xe ô tô chở người đến 9 chỗ ngồi?",
                "1. 16 tuổi.",
                "2. 18 tuổi.",
                "3. 17 tuổi.",
                null,
                "Đáp án: 18 tuổi.",
                "Giải thích: Độ tuổi lấy bằng theo hạng (cách nhau 3 tuổi): 16: Xe dưới 50cm3; 18: Hạng A, B1, B2; 21: Hạng C, FB; 24: Hạng D, FC; 27: Hạng E, FD.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 36: Người đủ 16 tuổi được điều khiển các loại xe nào dưới đây?",
                "1. Xe mô tô 2 bánh có dung tích xi lanh từ 50 cm3 trở lên.",
                "2. Xe gắn máy có dung tích xi lanh dưới 50 cm3.",
                "3. Xe ô tô tải dưới 3,5 tấn; xe chở người đến 9 chỗ ngồi.",
                "4. Tất cả các ý nêu trên.",
                "Đáp án: Xe gắn máy có dung tích xi lanh dưới 50 cm3.",
                "Giải thích: Độ tuổi lấy bằng theo hạng (cách nhau 3 tuổi): 16: Xe dưới 50cm3; 18: Hạng A, B1, B2; 21: Hạng C, FB; 24: Hạng D, FC; 27: Hạng E, FD.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 37: Người có giấy phép lái xe mô tô hạng A1 không được phép điều khiển loại xe nào dưới đây?",
                "1. Xe mô tô có dung tích xi lanh 125 cm3.",
                "2. Xe mô tô có dung tích xi lanh từ 175 cm3 trở lên.",
                "3. Xe mô tô có dung tích xi lanh 100 cm3.",
                null,
                "Đáp án: Xe mô tô có dung tích xi lanh từ 175 cm3 trở lên.",
                "Giải thích: A1 mô tô dưới 175cm3 và xe 3 bánh của người khuyết tật; A2 mô tô 175cm3 trở lên; A3 xe 3 bánh.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 38: Người có giấy phép lái xe mô tô hạng A1 được phép điều khiển loại xe nào dưới đây?",
                "1. Xe mô tô hai bánh có dung tích xi lanh từ 50 cm3 đến dưới 175 cm3.",
                "2. Xe mô tô ba bánh dùng cho người khuyết tật.",
                "3. Cả ý 1 và ý 2.",
                null,
                "Đáp án: Cả ý 1 và ý 2.",
                "Giải thích: A1 mô tô dưới 175cm3 và xe 3 bánh của người khuyết tật; A2 mô tô 175cm3 trở lên; A3 xe 3 bánh.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 43: Khi sử dụng giấy phép lái xe đã khai báo mất để điều khiển phương tiện cơ giới đường bộ, ngoài việc bị thu hồi giấy phép lái xe, chịu trách nhiệm trước pháp luật, người lái xe không được cấp giấy phép lái xe trong thời gian bao nhiêu năm?",
                "1. 02 năm.",
                "2. 03 năm.",
                "3. 05 năm.",
                "4. 04 năm",
                "Đáp án: 05 năm.",
                "Giải thích: 05 năm không cấp lại nếu sử dụng bằng lái đã khai báo mất.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 46: Tại nơi có biển báo hiệu cố định lại có báo hiệu tạm thời thì người tham gia giao thông phải chấp hành hiệu lệnh của báo hiệu nào?",
                "1. Biển báo hiệu cố định.",
                "2. Báo hiệu tạm thời.",
                null,
                null,
                "Đáp án: Báo hiệu tạm thời.",
                "Giải thích: ưu tiên biển báo tạm thời.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 47: Trên đường có nhiều làn đường cho xe đi cùng chiều được phân biệt bằng vạch kẻ phân làn đường, người điều khiển phương tiện phải cho xe đi như thế nào?",
                "1. Cho xe đi trên bất kỳ làn đường nào hoặc giữa hai làn đường nếu không có xe phía trước; khi cần thiết phải chuyển làn đường, người lái xe phải quan sát xe phía trước để bảo đảm an toàn.",
                "2. Phải cho xe đi trong một làn đường và chỉ được chuyển làn đường ở những nơi cho phép; khi chuyển làn phải có tín hiệu báo trước và phải bảo đảm an toàn.",
                "3. Phải cho xe đi trong một làn đường, khi cần thiết phải chuyển làn đường, người lái xe phải quan sát xe phía trước để bảo đảm an toàn.",
                null,
                "Đáp án: Phải cho xe đi trong một làn đường và chỉ được chuyển làn đường ở những nơi cho phép; khi chuyển làn phải có tín hiệu báo trước và phải bảo đảm an toàn.",
                "Giải thích: Chuyển làn đường phải có tín hiệu báo trước.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 48: Trên đường một chiều có vạch kẻ phân làn đường, xe thô sơ và xe cơ giới phải đi như thế nào là đúng quy tắc giao thông?",
                "1. Xe thô sơ phải đi trên làn đường bên trái ngoài cùng, xe cơ giới, xe máy chuyên dùng đi trên làn đường bên phải.",
                "2. Xe thô sơ phải đi trên làn đường bên phải trong cùng, xe cơ giới, xe máy chuyên dùng đi trên làn đường bên trái.",
                "3. Xe thô sơ đi trên làn đường phù hợp không gây cản trở giao thông, xe cơ giới, xe máy chuyên dùng đi trên làn đường bên phải.",
                null,
                "Đáp án: Xe thô sơ phải đi trên làn đường bên phải trong cùng, xe cơ giới, xe máy chuyên dùng đi trên làn đường bên trái.",
                "Giải thích: Xe thô sơ phải đi làn đường bên phải trong cùng.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 49: Bạn đang lái xe trong khu vực đô thi từ 22 giờ đến 5 giờ sáng hôm sau và cần vượt một xe khác, bạn cần báo hiệu như thế nào để đảm bảo an toàn giao thông?",
                "1. Phải báo hiệu bằng đèn hoặc còi.",
                "2. Chỉ được báo hiệu bằng còi.",
                "3. Phải báo hiệu bằng cả còi và đèn.",
                "4. Chỉ báo hiệu bằng đèn.",
                "Đáp án: Chỉ báo hiệu bằng đèn.",
                "Giải thích: Chỉ sử dụng còi từ 5 giờ sáng đến 22 giờ tối. Nên phải sử dụng đèn để báo hiệu.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 50: Khi điều khiển xe chạy trên đường biết có xe sau xin vượt nếu đủ điều kiện an toàn người lái xe phải làm gì?",
                "1. Tăng tốc độ và ra hiệu cho xe sau vượt, không được gây trở ngại cho xe sau vượt.",
                "2. Người điều khiển phương tiện phía trước phải giảm tốc độ, đi sát về bên phải của phần đường xe chạy cho đến khi xe sau đã vượt qua, không được gây trở ngại cho xe sau vượt.",
                "3. Cho xe tránh về bên trái mình và ra hiệu cho xe sau vượt; nếu có chướng ngại vật phía trước hoặc thiếu điều kiện an toàn chưa cho vượt được phải ra hiệu cho xe sau biết; cấm gây trở ngại cho xe xin vượt.",
                null,
                "Đáp án: Người điều khiển phương tiện phía trước phải giảm tốc độ, đi sát về bên phải của phần đường xe chạy cho đến khi xe sau đã vượt qua, không được gây trở ngại cho xe sau vượt.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 51: Khi muốn chuyển hướng, người lái xe phải thực hiện như thế nào để đảm bảo an toàn giao thông?",
                "1. Quan sát gương, ra tín hiệu, quan sát an toàn và chuyển hướng.",
                "2. Quan sát gương, giảm tốc độ, ra tín hiệu chuyển hướng, quan sát an toàn và chuyển hướng.",
                "3. Quan sát gương, tăng tốc độ, ra tín hiệu và chuyển hướng.",
                null,
                "Đáp án: Quan sát gương, giảm tốc độ, ra tín hiệu chuyển hướng, quan sát an toàn và chuyển hướng.",
                "Giải thích: Chuyển hướng phải giảm tốc độ.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 52: Khi tránh xe đi ngược chiều, các xe phải nhường đường như thế nào là đúng quy tắc giao thông?",
                "1. Nơi đường hẹp chỉ đủ cho một xe chạy và có chỗ tránh xe thì xe nào ở gần chỗ tránh hơn phải vào vị trí tránh, nhường đường cho xe kia đi.",
                "2. Xe xuống dốc phải nhường đường cho xe đang lên dốc; xe nào có chướng ngại vật phía trước phải nhường đường cho xe không có chướng ngại vật đi trước.",
                "3. Xe lên dốc phải nhường đường cho xe xuống dốc; xe nào không có chướng ngại vật đi phía trước phải nhường đường cho xe có chướng ngại vật đi trước.",
                "4. Cả ý 1 và ý 2.",
                "Đáp án: Cả ý 1 và ý 2.",
                "Giải thích: Tránh xe ngược chiều thì nhường đường qua đường hẹp và nhường xe lên dốc.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 53: Bạn đang lái xe trên đường hẹp, xuống dốc và gặp một xe đang đi lên dốc, bạn cần làm gì?",
                "1. Tiếp tục đi vì xe lên dốc phải nhường đường cho mình.",
                "2. Nhường đường cho xe lên dốc.",
                "3. Chỉ nhường đường khi xe lên dốc nháy đèn.",
                null,
                "Đáp án: Nhường đường cho xe lên dốc.",
                "Giải thích: Nhường đường cho xe lên dốc.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 54: Tại nơi đường giao nhau, người lái xe đang đi trên đường không ưu tiên phải nhường đường như thế nào là đúng quy tắc giao thông?",
                "1. Nhường đường cho xe đi ở bên phải mình tới.",
                "2. Nhường đường cho xe đi ở bên trái mình tới.",
                "3. Nhường đường cho xe đi trên đường ưu tiên hoặc đường chính từ bất kỳ hướng nào tới.",
                null,
                "Đáp án: Nhường đường cho xe đi trên đường ưu tiên hoặc đường chính từ bất kỳ hướng nào tới.",
                "Giải thích: Đường không ưu tiên nhường đường cho xe trên đường ưu tiên.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 55: Tại nơi đường giao nhau không có báo hiệu đi theo vòng xuyến, người điều khiển phương tiện phải nhường đường như thế nào là đúng quy tắc giao thông?",
                "1. Phải nhường đường cho xe đi đến từ bên phải.",
                "2. Xe báo hiệu xin đường trước xe đó được đi trước.",
                "3. Phải nhường đường cho xe đi đến từ bên trái.",
                null,
                "Đáp án: Phải nhường đường cho xe đi đến từ bên phải.",
                "Giải thích: Giao nhau không có vòng xuyến thì nhường xe đến từ bên phải.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 56: Tại nơi đường bộ giao nhau cùng mức với đường sắt chỉ có đèn tín hiệu hoặc chuông báo hiệu, khi đèn tín hiệu màu đỏ đã bật sáng hoặc có tiếng chuông báo hiệu, người tham gia giao thông phải dừng lại ngay và giữ khoảng cách tối thiểu bao nhiêu mét tính từ ray gần nhất?",
                "1. 5 mét.",
                "2. 3 mét.",
                "3. 4 mét.",
                null,
                "Đáp án: 5 mét.",
                "Giải thích: Đứng cách ray đường sắt 5m.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 57: Người điều khiển phương tiện tham gia giao thông trong hầm đường bộ ngoài việc phải tuân thủ các quy tắc giao thông còn phải thực hiện những quy định nào dưới đây?",
                "1. Xe cơ giới, xe máy chuyên dùng phải bật đèn; xe thô sơ phải bật đèn hoặc có vật phát sáng báo hiệu; chỉ được dùng xe, đỗ xe ở nơi quy định.",
                "2. Xe cơ giới phải bật đèn ngay cả khi đường hầm sáng; phải cho xe chạy trên một làn đường và chỉ chuyển làn ở nơi được phép; được quay đầu xe, lùi xe khi cần thiết.",
                "3. Xe máy chuyên dùng phải bật đèn ngay cả khi đường hầm sáng; phải cho xe chạy trên một làn đường và chỉ chuyển làn ở nơi được phép; được quay đầu xe, lùi xe khi cần thiết.",
                null,
                "Đáp án: Xe cơ giới, xe máy chuyên dùng phải bật đèn; xe thô sơ phải bật đèn hoặc có vật phát sáng báo hiệu; chỉ được dùng xe, đỗ xe ở nơi quy định.",
                "Giải thích: Trong hầm chỉ đường dừng xe, đỗ xe ở nơi quy định.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 58: Người ngồi trên xe mô tô 2 bánh, xe gắn máy phải đội mũ bảo hiểm có cài quai đúng quy cách khi nào ?",
                "1. Khi tham gia giao thông đường bộ.",
                "2. Chỉ khi đi trên đường chuyên dùng, đường cao tốc.",
                "3. Khi tham gia giao thông trên đường tỉnh lộ hoặc quốc lộ.",
                null,
                "Đáp án: Khi tham gia giao thông đường bộ.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 59: Người điều khiển xe mô tô hai bánh, xe gắn máy được phép chở tối đa 2 người trong những trường hợp nào?",
                "1. Chở người bệnh đi cấp cứu; trẻ em dưới 14 tuổi.",
                "2. Áp giải người có hành vi vi phạm pháp luật.",
                "3. Cả ý 1 và ý 2.",
                null,
                "Đáp án: Cả ý 1 và ý 2.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 60: Người điều khiển xe mô tô hai bánh, xe gắn máy không được thực hiện những hành vi nào dưới đây?",
                "1. Đi vào phần đường dành cho người đi bộ và phương tiện khác; sử dụng ô, điện thoại di động, thiết bị âm thanh (trừ thiết bị trợ thính), đi xe dàn hàng ngang.",
                "2. Chở 02 người; trong đó, có người bị bệnh đi cấp cứu hoặc trẻ em dưới 14 tuổi hoặc áp giải người có hành vi vi phạm pháp luật.",
                "3. Điều khiển phương tiện tham gia giao thông trên đường tỉnh lộ hoặc quốc lộ.",
                null,
                "Đáp án: Đi vào phần đường dành cho người đi bộ và phương tiện khác; sử dụng ô, điện thoại di động, thiết bị âm thanh (trừ thiết bị trợ thính), đi xe dàn hàng ngang.",
                "Giải thích: Xe mô tô 2 bánh không được đi vào phần đường cho người đi bộ.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 61: Người điều khiển xe mô tô hai bánh, xe gắn máy có được đi xe dàn hàng ngang; đi xe vào phần đường dành cho người đi bộ và phương tiện khác; sử dụng ô, điện thoại di động, thiết bị âm thanh (trừ thiết bị trợ thính) hay không ?",
                "1. Được phép nhưng phải đảm bảo an toàn.",
                "2. Không được phép.",
                "3. Được phép tùy từng hoàn cảnh, điều kiện cụ thể.",
                null,
                "Đáp án: Không được phép.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 62: Người lái xe phải giảm tốc độ thấp hơn tốc độ tối đa cho phép (có thể dừng lại một cách an toàn) trong trường hợp nào dưới đây?",
                "1. Khi có báo hiệu cảnh báo nguy hiểm hoặc có chướng ngại vật trên đường; khi chuyển hướng xe chạy hoặc tầm nhìn bị hạn chế; khi qua nơi đường giao nhau, nơi đường bộ giao nhau với đường sắt; đường vòng; đường có địa hình quanh co, đèo dốc.",
                "2. Khi qua cầu, cống hẹp; khi lên gần đỉnh dốc, khi xuống dốc, khi qua trường học, khu đông dân cư, khu vực đang thi công trên đường bộ; hiện trường xảy ra tai nạn giao thông.",
                "3. Khi điều khiển xe vượt xe khác trên đường quốc lộ, đường cao tốc.",
                "4. Cả ý 1 và ý 2.",
                "Đáp án: Cả ý 1 và ý 2.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 63: Tại ngã ba hoặc ngã tư không có đảo an toàn, người lái xe phải nhường đường như thế nào là đúng trong các trường hợp dưới đây?",
                "1. Nhường đường cho người đi bộ đang đi trên phần đường dành cho người đi bộ sang đường; nhường đường cho xe đi trên đường ưu tiên, đường chính từ bất kỳ hướng nào tới; nhường đường cho xe ưu tiên, xe đi từ bên phải đến.",
                "2. Nhường đường cho người đi bộ đang đứng chờ đi qua phần đường dành cho người đi bộ sang đường; nhường đường cho xe đi trên đường ngược chiều, đường nhánh từ bất kỳ hướng nào tới; nhường đường cho xe đi từ bên trái đến.",
                "3. Không phải nhường đường.",
                null,
                "Đáp án: Nhường đường cho người đi bộ đang đi trên phần đường dành cho người đi bộ sang đường; nhường đường cho xe đi trên đường ưu tiên, đường chính từ bất kỳ hướng nào tới; nhường đường cho xe ưu tiên, xe đi từ bên phải đến.",
                "Giải thích: Người lái xe phải nhường đường cho xe ưu tiên.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 64: Khi điều khiển xe cơ giới, người lái xe phải bật đèn tín hiệu báo rẽ trong trường hợp nào sau đây?",
                "1. Khi cho xe chạy thẳng.",
                "2. Trước khi thay đổi làn đường.",
                "3. Sau khi thay đổi làn đường.",
                null,
                "Đáp án: Trước khi thay đổi làn đường.",
                "Giải thích: Phải bật đèn tín hiệu rẽ trước khi thay đổi làn đường.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 65: Trên đoạn đường hai chiều không có giải phân cách giữa, người lái xe không được vượt xe khác trong các trường hợp nào dưới đây?",
                "1. Xe bị vượt bất ngờ tăng tốc độ và cố tình không nhường đường.",
                "2. Xe bị vượt giảm tốc độ và nhường đường.",
                "3. Phát hiện có xe đi ngược chiều.",
                "4. Cả ý 1 và ý 3.",
                "Đáp án: Cả ý 1 và ý 3.",
                "Giải thích: Không được vượt khi xe bị vượt bất ngờ tăng tốc hoặc phát hiện có xe đi ngược chiều.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 66: Người lái xe mô tô xử lý như thế nào khi cho xe mô tô phía sau vượt?",
                "1. Nếu đủ điều kiện an toàn, người lái xe phải giảm tốc độ, đi sát về bên phải của phần đường xe chạy cho đến khi xe sau đã vượt qua, không được gây trở ngại đối với xe xin vượt.",
                "2. Lái xe vào lề đường bên trái và giảm tốc độ để xe phía sau vượt qua, không được gây trở ngại đối với xe xin vượt.",
                "3. Nếu đủ điều kiện an toàn, người lái xe phải tăng tốc độ, đi sát về bên phải của phần đường chạy cho đến khi xe sau vượt qua.",
                null,
                "Đáp án: Nếu đủ điều kiện an toàn, người lái xe phải giảm tốc độ, đi sát về bên phải của phần đường xe chạy cho đến khi xe sau đã vượt qua, không được gây trở ngại đối với xe xin vượt.",
                "Giải thích: Xử lý cho xe sau vượt thì giảm tốc độ và đi về bên phải.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 67: Trong các trường hợp dưới đây, để bảo đảm an toàn khi tham gia giao thông, người lái xe mô tô cần thực hiện như thế nào?",
                "1. Phải đội mũ bảo hiểm đạt chuẩn, có cài quai đúng quy cách, mặc quần áo gọn gàng; không sử dụng ô, điện thoại di động, thiết bị âm thanh (trừ thiết bị trợ thính).",
                "2. Phải đội mũ bảo hiểm khi trời mưa gió hoặc trời quá nắng; có thể sử dụng ô, điện thoại di động, thiết bị âm thanh nhưng phải đảm bảo an toàn.",
                "3. Phải đội mũ bảo hiểm khi cảm thấy mất an toàn giao thông hoặc khi chuẩn bị di chuyển quãng đường xa.",
                null,
                "Đáp án: Phải đội mũ bảo hiểm đạt chuẩn, có cài quai đúng quy cách, mặc quần áo gọn gàng; không sử dụng ô, điện thoại di động, thiết bị âm thanh (trừ thiết bị trợ thính).",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 68: Đường bộ trong khu vực đông dân cư gồm những đoạn đường nào dưới đây?",
                "1. Là đoạn đường nằm trong khu công nghiệp có đông người và phương tiện tham gia giao thông và được xác định cụ thể bằng biển chỉ dẫn địa giới.",
                "2. Là đoạn đường bộ nằm trong khu vực nội thành phố, nội thị xã, nội thị trấn và những đoạn đường có đông dân cư sinh sống sát dọc theo đường, có các hoạt động ảnh hưởng đến an toàn giao thông; được xác định bằng biển báo hiệu là đường khu đông dân cư.",
                "3. Là đoạn đường nằm ngoài khu vực nội thành phố, nội thị xã có đông người và phương tiện tham gia giao thông và được xác định cụ thể bằng biển chỉ dẫn địa giới.",
                null,
                "Đáp án: Là đoạn đường bộ nằm trong khu vực nội thành phố, nội thị xã, nội thị trấn và những đoạn đường có đông dân cư sinh sống sát dọc theo đường, có các hoạt động ảnh hưởng đến an toàn giao thông; được xác định bằng biển báo hiệu là đường khu đông dân cư.",
                "Giải thích: Đường bộ trong khu vực đông dân cư được xác định bằng biển báo.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 69: Tốc độ tối đa cho phép đối với xe máy chuyên dùng, xe gắn máy (kể cả xe máy điện) và các loại xe tương tự trên đường bộ (trừ đường cao tốc) không được vượt quá bao nhiêu km/h?",
                "1. 50 km/h.",
                "2. 40 km/h.",
                "3. 60 km/h.",
                null,
                "Đáp án: 40 km/h.",
                "Giải thích: Xe gắn máy tối đa 40km/h.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 70: Trên đường bộ (trừ đường cao tốc) trong khu vực đông dân cư, đường đôi có dải phân cách giữa, xe mô tô hai bánh, ô tô chở người đến 30 chỗ tham gia giao thông với tốc độ tối đa cho phép là bao nhiêu?",
                "1. 60 km/h.",
                "2. 50 km/h.",
                "3. 40 km/h.",
                null,
                "Đáp án: 60 km/h.",
                "Giải thích: Có giải phân cách giữa thì được xem là đường đôi. Trong khu vực đông dân cư, đường đôi; đường một chiều có từ hai làn xe cơ giới trở lên: 60km/h.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 71: Trên đường bộ (trừ đường cao tốc) trong khu vực đông dân cư, đường hai chiều không có dải phân cách giữa, xe mô tô hai bánh, ô tô chở người đến 30 chỗ tham gia giao thông với tốc độ tối đa cho phép là bao nhiêu?",
                "1. 60 km/h.",
                "2. 50 km/h.",
                "3. 40 km/h.",
                null,
                "Đáp án: 50 km/h.",
                "Giải thích: Trong khu vực đông dân cư, đường hai chiều; đường một chiều có một làn xe cơ giới: 50km/h.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 72: Trên đường bộ (trừ đường cao tốc) trong khu vực đông dân cư, đường hai chiều hoặc đường một chiều có một làn xe cơ giới, loại xe nào dưới đây được tham gia giao thông với tốc độ tối đa cho phép là 50 km/h?",
                "1. Ô tô con, ô tô tải, ô tô chỏ người trên 30 chỗ.",
                "2. Xe gắn máy, xe máy chuyên dùng.",
                "3. Cả ý 1 và ý 2.",
                null,
                "Đáp án: Ô tô con, ô tô tải, ô tô chỏ người trên 30 chỗ.",
                "Giải thích: Xe cơ giới không bao gồm xe gắn máy. Trong khu vực đông dân cư, đường hai chiều; đường một chiều có một làn xe cơ giới: 50km/h.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 73: Khi điều khiển xe chạy với tốc độ dưới 60 km/h, để đảm bảo khoảng cách an toàn giữa hai xe, người lái xe phải điều khiển xe như thế nào?",
                "1. Chủ động giữ khoảng cách an toàn phù hợp với xe chạy liền trước xe của mình.",
                "2. Đảm bảo khoảng cách an toàn theo mật độ phương tiện, tình hình giao thông thực tế.",
                "3. Cả ý 1 và ý 2.",
                null,
                "Đáp án: Cả ý 1 và ý 2.",
                "Giải thích: Khoảng cách an toàn dưới 60km/h: Chủ động và đảm bảo khoảng cách.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 74: Người lái xe phải giảm tốc độ thấp hơn tốc độ tối đa cho phép đến mức cần thiết, chú ý quan sát và chuẩn bị sẵn sàng những tình huống có thể xảy ra để phòng ngừa tai nạn trong các trường hợp nào dưới đây?",
                "1. Gặp biển báo nguy hiểm trên đường.",
                "2. Gặp biển chỉ dẫn trên đường.",
                "3. Gặp biển báo hết mọi lệnh cấm.",
                "4. Gặp biển báo hết hạn chế tốc độ tối đa cho phép.",
                "Đáp án: Gặp biển báo nguy hiểm trên đường.",
                "Giải thích: Giảm tốc độ, chú ý quan sát khi gặp biển báo nguy hiểm.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 75: Các phương tiện tham gia giao thông đường bộ (kể cả những xe có quyền ưu tiên) đều phải dừng lại bên phải đường của mình và trước vạch “dừng xe” tại các điểm giao cắt giữa đường bộ và đường sắt khi có báo hiệu dừng nào dưới đây?",
                "1. Hiệu lệnh của nhân viên gác chắn.",
                "2. Đèn đỏ sáng nháy, cờ đỏ, biển đỏ.",
                "3. Còi, chuông kêu, chắn đã đóng.",
                "4. Tất cả các ý trên.",
                "Đáp án: Tất cả các ý trên.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 76: Tác dụng của mũ bảo hiểm đối với người ngồi trên xe mô tô hai bánh trong trường hợp xảy ra tai nạn giao thông là gì?",
                "1. Để làm đẹp.",
                "2. Để tránh mưa nắng.",
                "3. Để giảm thiểu chấn thương vùng đầu.",
                "4. Để các loại phương tiện khác dễ quan sát.",
                "Đáp án: Để giảm thiểu chấn thương vùng đầu.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 77: Tại nơi đường giao nhau, người lái xe đang đi trên đường không ưu tiên phải xử lý như thế nào là đúng quy tắc giao thông?",
                "1. Tăng tốc độ qua đường giao nhau để đi trước xe đi trên đường ưu tiên.",
                "2. Giảm tốc độ qua đường giao nhau để đi trước xe đi trên đường ưu tiên.",
                "3. Nhường đường cho xe đi trên ưu tiên từ bất kỳ hướng nào tới.",
                null,
                "Đáp án: Nhường đường cho xe đi trên ưu tiên từ bất kỳ hướng nào tới.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 78: Người lái xe phải xử lý như thế nào khi quan sát phía trước thấy người đi bộ đang sang đường tại nơi có vạch đường dành cho người đi bộ để đảm bảo an toàn?",
                "1. Giảm tốc độ, đi từ từ đế vượt qua trước người đi bộ.",
                "2. Giảm tốc độ, có thể dừng lại nếu cần thiết trước vạch dừng xe để nhường đường cho người đi bộ qua đường.",
                "3. Tăng tốc độ để vượt qua trước người đi bộ.",
                null,
                "Đáp án: Giảm tốc độ, có thể dừng lại nếu cần thiết trước vạch dừng xe để nhường đường cho người đi bộ qua đường.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 79: Theo Luật Giao thông đường bộ, tín hiệu đèn giao thông gồm 3 màu nào dưới đây?",
                "1. Đỏ – Vàng – Xanh.",
                "2. Cam – Vàng – Xanh.",
                "3. Vàng – Xanh dương – Xanh lá.",
                "4. Đỏ – Cam – Xanh.",
                "Đáp án: Đỏ – Vàng – Xanh.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 80: Tại nơi đường giao nhau, khi đèn điều khiển giao thông có tín hiệu màu vàng, người điều khiển giao thông phải chấp hành như thế nào là đúng quy tắc giao thông?",
                "1. Phải cho xe dừng lại trước vạch dừng, trường hợp đã đi quá vạch dừng hoặc đã quá gần vạch dừng nếu dừng lại thấy nguy hiểm thì được đi tiếp.",
                "2. Trong trường hợp tín hiệu vàng nhấp nháy là được đi nhưng phải giảm tốc độ, chú ý quan sát nhường đường cho người đi bộ qua đường.",
                "3. Nhanh chóng tăng tốc độ, vượt qua nút giao và chú ý đảm bảo an toàn.",
                "4. Cả ý 1 và ý 2.",
                "Đáp án: Cả ý 1 và ý 2.",
                "Giải thích: Đèn vàng dừng lại trước vạch dừng hoặc nhấp nháy thì đi chậm.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 81: Để báo hiệu cho xe phía trước biết xe mô tô của bạn muốn vượt, bạn phải có tín hiệu như thế nào dưới đây?",
                "1. Ra tín hiệu bằng tay rồi cho xe vượt qua.",
                "2. Tăng ga mạnh để gây sự chú ý rồi cho xe vượt qua.",
                "3. Bạn phải có tín hiệu bằng đèn hoặc còi.",
                null,
                "Đáp án: Bạn phải có tín hiệu bằng đèn hoặc còi.",
                "Giải thích: Muốn vượt xe thì phải báo hiệu bằng đèn hoặc còi.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 82: Người điều khiển xe mô tô phải giảm tốc độ và hết sức thận trọng khi qua những đoạn đường nào dưới đây?",
                "1. Đường ướt, đường có sỏi cát trên nền đường.",
                "2. Đường hẹp có nhiều điểm giao cắt từ hai phía.",
                "3. Đường đèo dốc, vòng liên tục.",
                "4. Tất cả các ý nêu trên.",
                "Đáp án: Tất cả các ý nêu trên.",
                "Giải thích: Giảm tốc độ trên đường ướt, đường hẹp và đèo dốc.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 83: Khi gặp xe buýt đang dừng đón, trả khách, người điều khiển xe mô tô phải xử lý như thế nào dưới đây để đảm bảo an toàn giao thông?",
                "1. Tăng tốc độ để nhanh chóng vượt qua bến đỗ.",
                "2. Giảm tốc độ đến mức an toàn có thể và quan sát người qua đường và từ từ vượt qua xe buýt.",
                "3. Yêu cầu phải dừng lại phía sau xe buýt chờ xe rời bến mới đi tiếp.",
                null,
                "Đáp án: Giảm tốc độ đến mức an toàn có thể và quan sát người qua đường và từ từ vượt qua xe buýt.",
                "Giải thích: Xe buýt đang dừng đón trả khách thì giảm tốc độ và từ từ vượt qua xe buýt.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 84: Khái niệm về văn hóa giao thông được hiểu như thế nào là đúng?",
                "1. Là sự hiểu biết và chấp hành nghiêm chỉnh pháp luật về giao thông; là ý thức trách nhiệm với cộng đồng khi tham gia giao thông.",
                "2. Là ứng xử có văn hóa, có tình yêu thương con người trong các tình huống không may xảy ra khi tham gia giao thông.",
                "3. Cả ý 1 và ý 2.",
                null,
                "Đáp án: Cả ý 1 và ý 2.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 85: Trong các hành vi dưới đây, người lái xe mô tô có văn hóa giao thông phải ứng xử như thế nào?",
                "1. Điều khiển xe đi bên phải theo chiều đi của mình; đi đúng phần đường, làn đường quy định; đội mũ bảo hiểm đạt chuẩn, cài quai đúng quy định.",
                "2. Điều khiển xe đi trên phần đường, làn đường có ít phương tiện tham gia giao thông.",
                "3. Điều khiển xe và đội mũ bảo hiểm ở nơi có biển báo bắt buộc đội mũ bảo hiểm.",
                null,
                "Đáp án: Điều khiển xe đi bên phải theo chiều đi của mình; đi đúng phần đường, làn đường quy định; đội mũ bảo hiểm đạt chuẩn, cài quai đúng quy định.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 86: Trong các hành vi dưới đây, người lái xe ô tô, mô tô có văn hóa giao thông phải ứng xử như thế nào?",
                "1. Điều khiển xe đi bên phải theo chiều đi của mình; đi đúng phần đường, làn đường quy định; dừng, đỗ xe đúng nơi quy định; đã uống rượu, bia thì không lái xe.",
                "2. Điều khiển xe đi trên phần đường, làn đường có ít phương tiện giao thông; dừng xe, đỗ xe ở nơi thuận tiện hoặc theo yêu cầu của hành khách, của người thân.",
                "3. Dừng và đỗ xe ở nơi thuận tiện cho việc chuyên chở hành khách và giao nhận hàng hóa; sử dụng ít rượu, bia thì có thể lái xe.",
                null,
                "Đáp án: Điều khiển xe đi bên phải theo chiều đi của mình; đi đúng phần đường, làn đường quy định; dừng, đỗ xe đúng nơi quy định; đã uống rượu, bia thì không lái xe.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 87: Khi xảy ra tai nạn giao thông, có người bị thương nghiêm trọng, người lái xe và người có mặt tại hiện trường vụ tai nạn phải thực hiện các công việc gì dưới đây?",
                "1. Thực hiện sơ cứu ban đầu trong trường hợp khẩn cấp; thông báo vụ tai nạn đến cơ quan thi hành pháp luật.",
                "2. Nhanh chóng lái xe gây tai nạn hoặc đi nhờ xe khác ra khỏi hiện tượng vụ tai nạn.",
                "3. Cả ý 1 và ý 2.",
                null,
                "Đáp án: Thực hiện sơ cứu ban đầu trong trường hợp khẩn cấp; thông báo vụ tai nạn đến cơ quan thi hành pháp luật.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 88: Trên đường đang xảy ra ùn tắc có những hành vi nào sau đây là thiếu văn hóa khi tham gia giao thông?",
                "1. Bấm còi liên tục thúc giục các phương tiện phía trước nhường đường.",
                "2. Đi lên vỉa hè, tận dùng mọi khoảng trống để nhanh chóng thoát khỏi nơi ùn tắc.",
                "3. Lấn sàng trái đường cố gắng vượt lên xe khác.",
                "4. Tất cả các ý nêu trên.",
                "Đáp án: Tất cả các ý nêu trên.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 89: Khi điều khiển xe mô tô tay ga xuống đường dốc dài, độ dốc cao, người lái xe cần thực hiện các thao tác nào dưới đây để đảm bảo an toàn?",
                "1. Giữ tay ga ở mức độ phù hợp, sử dụng phanh trước và phanh sau để giảm tốc độ.",
                "2. Nhả hết tay ga, tắt động cơ, sử dụng phanh trước và phanh sau để giảm tốc độ.",
                "3. Sử dụng phanh trước để giảm tốc độ kết hợp với tắt chìa khóa điện của xe.",
                null,
                "Đáp án: Giữ tay ga ở mức độ phù hợp, sử dụng phanh trước và phanh sau để giảm tốc độ.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 90: Khi quay đầu xe, người lái xe cần phải quan sát và thực hiện các thao tác nào để đảm bảo an toàn giao thông?",
                "1. Quan sát biển báo hiệu để biết nơi được phép quay đầu; quan sát kỹ địa hình nơi chọn để quay đầu; lựa chọn quỹ đạo quay đầu xe cho thích hợp; quay đầu xe với tốc độ thấp; thường xuyên báo tín hiệu để người, các phương tiện xung quanh được biết; nếu quay đầu xe ở nơi nguy hiểm thì đưa đầu xe về phía nguy hiểm đưa đuôi xe về phía an toàn.",
                "2. Quan sát biển báo hiệu để biết nơi được phép quay đầu; quan sát kỹ địa hình nơi chọn để quay đầu; lựa chọn quỹ đạo quay đầu xe; quay đầu xe với tốc độ tối đa; thường xuyên báo tín hiệu để người, các phương tiện xung quanh được biết; nếu quay đầu xe ở nơi nguy hiểm thì đưa đuôi xe về phía nguy hiểm và đầu xe về phía an toàn.",
                null,
                null,
                "Đáp án: Quan sát biển báo hiệu để biết nơi được phép quay đầu; quan sát kỹ địa hình nơi chọn để quay đầu; lựa chọn quỹ đạo quay đầu xe cho thích hợp; quay đầu xe với tốc độ thấp; thường xuyên báo tín hiệu để người, các phương tiện xung quanh được biết; nếu quay đầu xe ở nơi nguy hiểm thì đưa đầu xe về phía nguy hiểm đưa đuôi xe về phía an toàn.",
                "Giải thích: Thực hiện quay đầu xe với tốc độ thấp.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 91: Khi tránh nhau trên đường hẹp, người lái xe cần phải chú ý những điểm nào để đảm bảo an toàn giao thông?",
                "1. Không nên đi cố vào đường hẹp; xe đi ở phía sườn núi nên dừng lại trước để nhường đường; khi dừng xe nhường đường phải đỗ ngay ngắn.",
                "2. Trong khi tránh nhau không nơi đổi số; khi tránh nhau ban đêm, phải tắt đèn pha bật đèn cốt.",
                "3. Khi tránh nhau ban đêm, phải thường xuyên bật đèn pha tắt đèn cốt.",
                "4. Cả ý 1 và ý 2.",
                "Đáp án: Cả ý 1 và ý 2.",
                "Giải thích: Cả ý 1 và 2 đều đúng. Ý 3 tránh nhau ban đêm bật đèn pha là sai.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 92: Khi điều khiển xe trên đường vòng người lái xe cần phải làm gì để đảm bảo an toàn?",
                "1. Quan sát cẩn thận các chướng ngại vật và báo hiệu bằng còi, đèn; giảm tốc độ tới mức cần thiết, về số thấp và thực hiện quay vòng với tốc độ phù hợp với bán kính cong của đường vòng.",
                "2. Quan sát cẩn thận các chướng ngại vật và báo hiệu bằng còi, đèn; tăng tốc để nhanh chóng qua đường vòng và giảm tốc độ sau khi qua đường vòng.",
                null,
                null,
                "Đáp án: Quan sát cẩn thận các chướng ngại vật và báo hiệu bằng còi, đèn; giảm tốc độ tới mức cần thiết, về số thấp và thực hiện quay vòng với tốc độ phù hợp với bán kính cong của đường vòng.",
                "Giải thích: Điều khiển xe trên đường vòng cần giảm tốc độ.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 93: Để đạt được hiệu quả phanh cao nhất, người lái xe mô tô phải sử dụng các kỹ năng như thế nào dưới đây?",
                "1. Sử dụng phanh trước.",
                "2. Sử dụng phanh sau.",
                "3. Giảm hết ga; sử dụng đồng thời cả phanh sau và phanh trước.",
                null,
                "Đáp án: Giảm hết ga; sử dụng đồng thời cả phanh sau và phanh trước.",
                "Giải thích: Khi phanh xe mô tô thì giảm hết ga.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 94: Khi đang lái xe mô tô và ô tô, nếu có nhu cầu sử dụng điện thoại để nhắn tin hoặc gọi điện, người lái xe phải thực hiện như thế nào trong các tình huống nêu dưới đây?",
                "1. Giảm tốc độ để đảm bảo an toàn với xe phía trước và sử dụng điện thoại để liên lạc.",
                "2. Giảm tốc độ để dừng xe ở nơi cho phép dừng xe sau đó sử dụng điện thoại để liên lạc.",
                "3. Tăng tốc độ để cách xa xe phía sau và sử dụng điện thoại để liên lạc.",
                null,
                "Đáp án: Giảm tốc độ để dừng xe ở nơi cho phép dừng xe sau đó sử dụng điện thoại để liên lạc.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 95: Những thói quen nào dưới đây khi điều khiển xe mô tô tay ga tham gia giao thông dễ gây tai nạn nguy hiểm?",
                "1. Sử dụng còi.",
                "2. Phanh đồng thời cả phanh trước và phanh sau.",
                "3. Chỉ sử dụng phanh trước.",
                null,
                "Đáp án: Chỉ sử dụng phanh trước.",
                "Giải thích: Xe mô tô tay ga chỉ sử dụng phanh trước thì rất nguy hiểm.",
                0));
        arrayOntap.add(new OnTap("Câu hỏi 96: Khi điều khiển xe mô tô quay đầu người lái xe cần thực hiện như thế nào để đảm bảo an toàn?",
                "1. Bật tín hiệu báo rẽ trước khi quay đầu, từ từ giảm tốc độ đến mức có thể dừng lại.",
                "2. Chỉ quay đầu xe ở những nơi được phép quay đầu.",
                "3. Quan sát an toàn các phương tiện tới từ phía trước, phía sau, hai bên đồng thời nhường đường cho xe từ bên phải và phía trước đi tới.",
                "4. Tất cả các ý nêu trên.",
                "Đáp án: Tất cả các ý nêu trên.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 97: Tay ga trên xe mô tô hai bánh có tác dụng gì trong các trường hợp dưới đây?",
                "1. Để điều khiển xe chạy về phía trước.",
                "2. Để điều tiết công suất động cơ qua đó điều khiển tốc độ của xe.",
                "3. Để điều khiển xe chạy lùi.",
                "4. Cả ý 1 và ý 2.",
                "Đáp án: Cả ý 1 và ý 2.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 98: Gương chiếu hậu của xe mô tô hai bánh có tác dụng gì trong các trường hợp dưới đây?",
                "1. Để quan sát an toàn phía bên trái khi chuẩn bị rẽ trái.",
                "2. Để quan sát an toàn phía bên phải khi chuẩn bị rẽ phải.",
                "3. Để quan sát an toàn phía sau cả bên trái và bên phải trước khi chuyển hướng.",
                "4. Để quan sát an toàn phía trước cả bên trái và bên phải trước khi chuyển hướng.",
                "Đáp án: Để quan sát an toàn phía sau cả bên trái và bên phải trước khi chuyển hướng.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 99: Để đảm bảo an toàn khi tham gia giao thông, người lái xe mô tô hai bánh cần điều khiển tay ga như thế nào trong các trường hợp dưới đây?",
                "1. Tăng ga thật nhanh, giảm ga từ từ.",
                "2. Tăng ga thật nhanh, giảm ga thật nhanh.",
                "3. Tăng ga từ từ, giảm ga thật nhanh.",
                "4. Tăng ga từ từ, giảm ga từ từ.",
                "Đáp án: Tăng ga từ từ, giảm ga thật nhanh.",
                null,
                0));
        arrayOntap.add(new OnTap("Câu hỏi 100: Kỹ thuật cơ bản để giữ thăng bằng khi điều khiển xe mô tô đi trên đường gồ ghề như thế nào trong các trường hợp dưới đây?",
                "1. Đứng thẳng trên giá gác chân lái sau đó hơi gập đầu gối và khuỷu tay, đi chậm để không nẩy quá mạnh.",
                "2. Ngồi lùi lại phía sau, tăng ga vượt nhanh qua đoạn đường xóc.",
                "3. Ngồi lệch sang bên trái hoặc bên phải để lấy thăng bằng qua đoạn đường gồ ghề.",
                null,
                "Đáp án: Đứng thẳng trên giá gác chân lái sau đó hơi gập đầu gối và khuỷu tay, đi chậm để không nẩy quá mạnh.",
                null,
                0));


    }

}